[package]
name = "notifications"
version = "0.1.0-dev"
authors = ["Pieter Frenssen <pieter@frenssen.be>"]
edition = "2018"

[dependencies]
app = { path = "../app" }
db = { path = "../db" }
mailgun_v3 = { git = "https://github.com/pfrenssen/mailgun_v3.git", branch = "configurable-api-endpoint" }
