language: rust
dist: bionic

rust:
  - stable
  - beta
  - nightly

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgres://travis@localhost/travis
    - SECRET_KEY=travis123

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

addons:
  postgresql: 11
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

before_install:
  - sudo apt-get update
  - sudo apt-get install php php-xml php-mbstring composer
  - php --version
  - rustup component add clippy
  - rustup component add rustfmt
  - cargo install diesel_cli --no-default-features --features "postgres" || true
  - diesel --version
  - diesel database setup

install:
  - composer install

script:
  # Compile the project.
  - cargo build
  # Check coding standards.
  - cargo fmt --all -- --check
  # Run clippy.
  - cargo clean --package firetrack
  - cargo clippy --all-targets --all-features -- -D warnings
  # Run Rust test suites.
  - cargo test --all
  # Start the webserver and wait for it to come online.
  - cargo run -- serve &> actix.log &
  - until curl -s localhost:8088; do true; done &> /dev/null
  # Run BDD test suite.
  - ./vendor/bin/behat
  # Show server log.
  - cat actix.log

before_cache:
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.rustup/toolchains/nightly*
  - rm -rf /home/travis/.rustup/update-hashes/nightly*
  - rm -rf /home/travis/build/pfrenssen/firetrack/target
