language: rust
# Using Xenial instead of Bionic because PostgreSQL doesn't work in Bionic.
# https://travis-ci.community/t/postgresql-fails-to-start/4558
dist: xenial

rust:
  - stable
  - beta
  - nightly

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/firetrack
    - SECRET_KEY=travis123

matrix:
  allow_failures:
    - rust: nightly

#cache: cargo

before_install:
  # Use a PPA to get a more recent version of PHP in Xenial.
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install php7.3 php7.3-xml php7.3-mbstring composer
  - php --version
  - rustup component add clippy
  - rustup component add rustfmt

install:
  # The version of Composer shipping with Xenial doesn't work with PHP 7.3.
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php composer.phar --version
  - php composer.phar install --no-interaction --prefer-source

before_script:
  - psql -c 'create database firetrack;' -U postgres

script:
  # Compile the project.
  - cargo build
  # Check coding standards.
  - cargo fmt --all -- --check
  # Run clippy.
  - cargo clean --package firetrack
  - cargo clippy --all-targets --all-features -- -D warnings
  # Run Rust test suites.
  - cargo test --all
  # Start the webserver and wait for it to come online.
  - cargo run -- serve &> actix.log &
  - until curl -s localhost:8088; do true; done &> /dev/null
  # Run BDD test suite.
  - ./vendor/bin/behat
  # Show server log.
  - cat actix.log
#  # Show how much data is cached.
#  - du -hs /home/travis/.cargo
#  - du -hs /home/travis/build/pfrenssen/firetrack/target
#  - du -hs /home/travis/.rustup
#  - du -hs /home/travis/.cache/sccache
