[package]
name = "app"
version = "0.1.0-dev"
authors = ["Pieter Frenssen <pieter@frenssen.be>"]
edition = "2018"

[dependencies]
dotenv = "~0.15"
env_logger = "~0.7"
mailgun_v3 = "~0.9"
mockito = "^0.25.1"
regex = "^1.3.6"
